### ISSUE TITLE
Transparent sprites

### ISSUE THREAD

**Issue by vrobik** [codedojo/battlecity-js#1]
я вам спрайты получьше сделал, без прозрачьности будут проблемы в будущем

[original](https://ibb.co/fYQ6rw4)
[transparent](https://ibb.co/B2xJzbS)

жду продолжения банкета 👍

**Comment by olegpolyakov** [comment]
@vrobik Ты бы мог сделать еще один вариант для другого размера изображения?
![sprite](https://user-images.githubusercontent.com/12645350/111506234-7bdfc100-875a-11eb-861e-7ddb6f058a8d.png)

**Comment by vrobik** [comment]
да, вот этот вроде под 32 пикселя
https://ibb.co/JCVQZsh
проверил с новыми изминениями вроде норм, если что переделаю

**Comment by olegpolyakov** [comment]
Спасибо!

**Comment by MyMarvel** [comment]
Для тех, кто ищет этот спрайт, его можно взять из этого проекта, сразу прозрачный, 32px: https://github.com/dogballs/cattle-bity/blob/master/data/graphics/sprite.png
